// GAAP Codex index + fuzzy search over all 99 FASB ASC Topics.
//
// Runs on the compact src/data/asc/ascIndex.json (≈50 KB: topic number, title, series, real-estate
// tier, tagline, aliases and subtopic titles), generated by scripts/build_asc_codification.py.
// Master cards and official text are never imported here — see data/asc/ascLoader.
//
// Pure JS (no React Native imports) so it can be unit-tested in Node.

import ASC_INDEX from '../data/asc/ascIndex.json';
import { normalize, editDistance } from './fuzzy';

/** FASB series in Codification order: { series, category, color, count, topics }. */
export const ASC_SERIES = ASC_INDEX.series;
const SERIES_BY_KEY = new Map(ASC_SERIES.map((s) => [s.series, s]));
export const getAscSeries = (series) => SERIES_BY_KEY.get(series) || null;

const words = (s) => normalize(s).split(' ').filter(Boolean);

export const ASC_TOPICS = ASC_INDEX.topics.map((raw) => {
  const series = SERIES_BY_KEY.get(raw.series);
  const aliases = raw.aliases.map(normalize);
  return {
    ...raw,
    category: series ? series.category : '',
    color: series ? series.color : '#94A3B8',
    // pre-normalized search text
    _title: normalize(raw.title),
    _titleWords: words(raw.title),
    _aliases: aliases,
    _aliasWords: Array.from(new Set(aliases.flatMap((a) => a.split(' ')))),
    _tag: normalize(raw.tag),
    _subWords: Array.from(new Set(raw.subtopics.flatMap(words))),
    _cat: normalize(series ? series.category : ''),
  };
});
const BY_TOPIC = new Map(ASC_TOPICS.map((e) => [e.topic, e]));

export const ASC_TOPIC_COUNT = ASC_TOPICS.length;
export const getAscEntry = (topic) => BY_TOPIC.get(String(topic)) || null;
export const hasAscTopic = (topic) => BY_TOPIC.has(String(topic));

// ── Filters ──────────────────────────────────────────────────────────────────────────────────
export const ASC_FILTERS = [
  { key: 're', label: 'Real Estate Relevant', short: 'Real Estate' },
  { key: 'core', label: 'Core Property Standards', short: 'Core RE' },
  { key: 'all', label: 'All US GAAP (Career Mastery)', short: 'All US GAAP' },
];

export function matchesFilter(entry, filter) {
  if (filter === 'core') return entry.re === 'core';
  if (filter === 're') return Boolean(entry.re);
  return true;
}

export const filterCount = (filter) => ASC_TOPICS.filter((e) => matchesFilter(e, filter)).length;

/** Group entries (already filtered/sorted) under their FASB series headers, in series order. */
export function groupBySeries(entries) {
  const groups = new Map();
  for (const e of entries) {
    if (!groups.has(e.series)) groups.set(e.series, []);
    groups.get(e.series).push(e);
  }
  return ASC_SERIES.filter((s) => groups.has(s.series)).map((s) => ({ ...s, data: groups.get(s.series) }));
}

// ── Query parsing ────────────────────────────────────────────────────────────────────────────
const PARA_RX = /^(?:asc\s*)?(\d{3})(?:-(\d{2,3}))?(?:-(S?\d{2}))?(?:-(\d+[A-Z]{0,2}))?$/i;
const STOP = new Set(['asc', 'topic', 'the', 'of', 'and', 'for', 'a', 'an', 'to', 'in', 'on', 'fasb']);

/**
 * Recognizes Codification references: "842", "ASC 842", "842-20", "842-20-25", "842-20-25-1".
 * @returns {{ topic: string, subtopic?: string, section?: string, paragraph?: string } | null}
 */
export function parseAscReference(query) {
  const q = String(query || '').trim().replace(/\s+/g, ' ').replace(/^asc\s*/i, '');
  const m = PARA_RX.exec(q);
  if (!m || !BY_TOPIC.has(m[1])) return null;
  const out = { topic: m[1] };
  if (m[2]) out.subtopic = m[2];
  if (m[3]) out.section = m[3].toUpperCase();
  if (m[2] && m[3] && m[4]) out.paragraph = `${m[1]}-${m[2]}-${m[3].toUpperCase()}-${m[4].toUpperCase()}`;
  return out;
}

function tokenScore(e, token) {
  if (/^\d+$/.test(token)) {
    if (token.length === 3) return e.topic === token ? 100 : 0;
    return e.topic.startsWith(token) ? 30 : 0;
  }
  // Short tokens ("vie", "rou", "eps") match only whole alias words or the start of a title word.
  const short = token.length <= 3;
  let best = 0;
  for (const w of e._titleWords) {
    if (w === token) return 14;
    if (w.startsWith(token)) best = Math.max(best, 10);
  }
  for (const w of e._aliasWords) {
    if (w === token) best = Math.max(best, 12);
    else if (!short && w.startsWith(token)) best = Math.max(best, 8);
  }
  if (best || short) return best;
  for (const w of e._subWords) if (w.startsWith(token)) return 6;
  if (token.length >= 3 && e._tag.includes(token)) return 4;
  if (e._cat.includes(token)) return 3;
  // typo tolerance: 1 edit for 4-6 letters, 2 edits for 7+
  if (token.length >= 4) {
    const max = token.length >= 7 ? 2 : 1;
    for (const w of e._titleWords.concat(e._aliasWords)) {
      if (w.length >= 3 && editDistance(token, w, max) <= max) return 3;
    }
  }
  return 0;
}

/**
 * Fuzzy search by Topic number, title, alias ("VIE", "stock comp", "ROU"), tagline or subtopic.
 * Every query token must match. Codification references ("842-20-25-1") resolve to their Topic.
 * @returns {{ results: Array, total: number, reference: object|null }}
 */
export function searchAsc(query, { filter = 'all', limit = ASC_TOPIC_COUNT } = {}) {
  const reference = parseAscReference(query);
  if (reference) {
    const e = BY_TOPIC.get(reference.topic);
    const results = matchesFilter(e, filter) ? [e] : [];
    return { results, total: results.length, reference };
  }
  const q = normalize(query);
  if (!q) {
    const all = ASC_TOPICS.filter((e) => matchesFilter(e, filter));
    return { results: all.slice(0, limit), total: all.length, reference: null };
  }
  const tokens = Array.from(new Set(q.split(' ').filter((t) => t && !STOP.has(t))));
  if (!tokens.length) return { results: [], total: 0, reference: null };
  const scored = [];
  for (const e of ASC_TOPICS) {
    if (!matchesFilter(e, filter)) continue;
    let score = 0;
    let ok = true;
    for (const t of tokens) {
      const s = tokenScore(e, t);
      if (!s) {
        ok = false;
        break;
      }
      score += s;
    }
    if (!ok) continue;
    const phrase = tokens.join(' ');
    if (e._aliases.includes(phrase)) score += 40;
    else if (e._aliases.some((a) => a.startsWith(phrase))) score += 15;
    if (e._title === phrase) score += 25;
    else if (e._title.includes(phrase)) score += 10;
    if (e.re === 'core') score += 1.5;
    else if (e.re) score += 0.5;
    if (e.legacy) score -= 8;
    scored.push({ e, score });
  }
  scored.sort((a, b) => b.score - a.score || a.e.topic.localeCompare(b.e.topic));
  return { results: scored.slice(0, limit).map((s) => s.e), total: scored.length, reference: null };
}
