// Deduction Compass engine: the filing logic behind RealPage menus, run fully offline.
//
// src/data/compassRules.json and src/data/compassIndex.json are generated by
// scripts/build_realpage_modules.py from scripts/rp_compass.py, the single source of the rules.
// deduce() below is a line-by-line port of rp_compass.deduce(); scripts/test/compass.test.mjs
// replays the Python predictions in scripts/output/compass_parity.json to keep the two identical.
//
// Pure JS (no React Native imports) so it can be unit-tested in Node.

import RULES from '../data/compassRules.json';
import COMPASS_INDEX from '../data/compassIndex.json';
import { ALL_SCREEN_ENTRIES } from './screenIndex';
import { normalize } from './fuzzy';

// ---------------------------------------------------------------------------
// Compiled rules
// ---------------------------------------------------------------------------

const rx = (pattern) => new RegExp(pattern, 'i');
const rxAll = (pattern) => new RegExp(pattern, 'gi');

const VERBS = RULES.verbs.map((v) => ({ ...v, re: rx(v.match) }));
const STATES = RULES.states.map((s) => ({ ...s, re: rx(s.match), reAll: rxAll(s.match) }));
const SYNONYMS = RULES.synonyms.map((s) => ({ re: rxAll(s.match), replace: s.replace }));
const OBJECTS = RULES.objects.map((o) => ({ ...o, re: rx(o.match), listRes: o.lists.map((li) => rx(li.match)) }));
const OBJECT_BY_ID = new Map(OBJECTS.map((o) => [o.id, o]));
const TIES = RULES.tieBreakers
  .filter((t) => t.trigger)
  .map((t) => ({ ...t, re: rx(t.trigger), unlessRe: t.unless ? rx(t.unless) : null }));
const TIE_BY_ID = new Map(RULES.tieBreakers.map((t) => [t.id, t]));
const CODE_NOUN = rx(RULES.codeNoun);
const STRONG_CONFIG = rx(RULES.strongConfig);
const FROM_CLAUSE = rx(RULES.fromClause);
const EXCEPTIONS = RULES.exceptions.map((e) => ({ ...e, cueRe: e.cue ? rx(e.cue) : null }));
const EXCEPTION_BY_ID = new Map(EXCEPTIONS.map((e) => [e.id, e]));

export const STAGES = RULES.stages; // { configure: { label, where, question }, … }
export const STAGE_KEYS = Object.keys(STAGES);
export const EXCEPTION_GROUPS = RULES.exceptionGroups;
export const getException = (id) => EXCEPTION_BY_ID.get(id) || null;
export const getObject = (id) => OBJECT_BY_ID.get(id) || null;

const SETUP_CONFIGURATION = { tab: 'Setup', section: null, submenu: 'Configuration' };

export const stageOfLocation = (tab, section) => (tab === 'Setup' ? 'configure' : RULES.stageOfSection[section] || null);

// Python's str.title(): capitalize every letter run.
const titleCase = (s) => s.toLowerCase().replace(/(^|[^a-z])([a-z])/g, (m, p, c) => p + c.toUpperCase());

function actionOf(text) {
  for (const v of VERBS) if (v.re.test(text)) return { stage: v.stage, action: v.action };
  return { stage: null, action: null };
}

function stateOf(text) {
  for (const s of STATES) if (s.re.test(text)) return s.state;
  return null;
}

export function normalizeScenario(text) {
  let out = text || '';
  for (const s of SYNONYMS) out = out.replace(s.re, s.replace);
  return out;
}

function stripStates(text) {
  let out = text;
  for (const s of STATES) out = out.replace(s.reAll, ' ');
  return out.replace(/\s+/g, ' ').trim();
}

export const objectsIn = (text) => OBJECTS.filter((o) => o.re.test(text || ''));

/**
 * Step 1: the business object that decides the application, and the tie-breaker that fired.
 * Tie-breakers read the full task; objects are matched on `text` (the task without its
 * record-state phrases, when it has one).
 */
function pickObject(full, text = full) {
  for (const t of TIES) {
    if (t.re.test(full) && !(t.unlessRe && t.unlessRe.test(full))) return { obj: OBJECT_BY_ID.get(t.force), tie: t.id };
  }
  const objs = objectsIn(text);
  if (!objs.length) return { obj: null, tie: null };
  const m = FROM_CLAUSE.exec(text);
  if (m) {
    const src = objectsIn(m[2]);
    if (src.length && src[0].kind !== 'service' && src[0].app !== objs[0].app) return { obj: src[0], tie: 'T7' };
  }
  const first = objs[0];
  if (first.id === 'bs_rec_report') return { obj: first, tie: 'T6' };
  if (new Set(objs.map((o) => o.app)).size > 1) return { obj: first, tie: 'T1' };
  return { obj: first, tie: null };
}

function titleSubmenu(text) {
  const t = text.replace(/^(customizing and running|customizing and creating|customizing|running|printing|viewing|using) (the |a )?/i, '');
  return t.replace(/\s+(report|chart|graph|list|page)s?(\s+options)?$/i, '').trim();
}

/**
 * Run the 3-step compass on a screen title, or (scenario: true) on a typed situation.
 * @returns {{object, app, stage, action, state, tab, section, submenu, rules: string[]}}
 */
export function deduce(input, { scenario = false } = {}) {
  let text = (input || '').trim();
  const state = stateOf(text);
  if (scenario) text = normalizeScenario(text);
  const { obj, tie } = pickObject(text, state ? stripStates(text) : text);
  const { stage, action } = actionOf(text);
  const rules = tie ? [tie] : [];
  if (!obj) return { object: null, app: null, stage, action, state, tab: null, section: null, submenu: null, rules };
  rules.push(`A:${obj.id}`);
  let landing = null;
  let why = null;
  // Step 3 first when the task names one of the object's own lists …
  for (let i = 0; i < obj.lists.length; i++) {
    if (obj.listRes[i].test(text)) {
      landing = obj.lists[i];
      why = `L:${obj.id}:${i}`;
      break;
    }
  }
  // … but "configure / enable" always means the Setup tab.
  if (STRONG_CONFIG.test(text) && (!landing || landing.tab !== 'Setup')) {
    landing = obj.setup || SETUP_CONFIGURATION;
    why = 'S:configure';
  }
  if (!landing) {
    // Step 2: tab / section from the verb and the kind of object
    if (obj.kind === 'code' || (CODE_NOUN.test(text) && obj.kind !== 'output')) {
      landing = obj.kind === 'code' ? obj.home : obj.setup || SETUP_CONFIGURATION;
      why = 'S:configure';
    } else if (stage === 'review' && obj.report) {
      landing = obj.report;
      why = 'S:review';
    } else if (stage === 'enter' && obj.daily && ['create', 'pay', 'receive'].includes(action)) {
      landing = obj.daily;
      why = 'S:enter';
    } else {
      landing = obj.home;
      why = `S:${RULES.stageOfKind[obj.kind]}`;
    }
  }
  rules.push(why);
  let { tab, section, submenu } = landing;
  if (submenu === '=title') {
    submenu = scenario ? `${obj.label} reports` : titleSubmenu(text);
  } else if (scenario && submenu == null) {
    submenu = obj.label;
  } else if (submenu === '=noun') {
    const m = rx(landing.match).exec(text);
    submenu = m ? titleCase(m[0]) : landing.submenu;
  }
  // Corrections to paid items: voiding a check is done from the Check Register (A/P › Reports).
  if ((obj.id === 'check' || obj.id === 'ap_invoice') && action === 'void') {
    tab = 'All';
    section = 'Reports';
    submenu = 'Check Register';
    rules.push('X:void-from-register');
  }
  return {
    object: obj.id,
    app: obj.app,
    stage: stageOfLocation(tab, section) || RULES.stageOfKind[obj.kind],
    action,
    state,
    tab,
    section,
    submenu,
    rules,
  };
}

// ---------------------------------------------------------------------------
// Explaining a deduction in plain English
// ---------------------------------------------------------------------------

/** Turns rule ids (T2, A:vendor, S:enter, L:check:0, X:…) into cards for the UI. */
export function explainRules(rules, pred) {
  const out = [];
  for (const id of rules || []) {
    if (id.startsWith('T')) {
      const t = TIE_BY_ID.get(id);
      if (t) out.push({ id, step: 1, title: `Tie-breaker ${id}: ${t.name}`, text: t.rule });
    } else if (id.startsWith('A:')) {
      const o = OBJECT_BY_ID.get(id.slice(2));
      out.push({ id, step: 1, title: `Noun → application: ${o.label}`, text: `The business object is “${o.label}”, which RealPage files under ${o.app}.` });
    } else if (id.startsWith('S:')) {
      const st = STAGES[id.slice(2)];
      if (st) out.push({ id, step: 2, title: `Stage → tab/section: ${st.label}`, text: `${st.question} → ${st.where}.` });
    } else if (id.startsWith('L:')) {
      const [, oid, idx] = id.split(':');
      const li = OBJECT_BY_ID.get(oid).lists[Number(idx)];
      const where = [li.tab, li.section, li.submenu].filter(Boolean).join(' › ');
      out.push({ id, step: 3, title: 'Noun → list', text: `The task names one of the object's own lists: ${pred && pred.submenu ? pred.submenu : li.submenu} (${where}).` });
    } else if (id === 'X:void-from-register') {
      const e = EXCEPTION_BY_ID.get('E34');
      out.push({ id, step: 3, title: e.title, text: e.why });
    }
  }
  return out;
}

export const formatPath = (loc) => [loc.app, loc.tab, loc.section, loc.submenu].filter(Boolean).join(' › ');

// ---------------------------------------------------------------------------
// Catalog joined with the compass tags (same order as searchIndex.json)
// ---------------------------------------------------------------------------

const F = COMPASS_INDEX;
if (F.rows.length !== ALL_SCREEN_ENTRIES.length) {
  throw new Error('compassIndex.json is out of sync with searchIndex.json; run npm run build:modules');
}

export const COMPASS_ENTRIES = ALL_SCREEN_ENTRIES.map((entry, i) => {
  const [app, tab, section, submenu, stage, object, fit, exc, kind] = F.rows[i];
  return {
    entry,
    id: entry.id,
    name: entry.name,
    app: app == null ? null : F.apps[app],
    tab: tab == null ? null : F.tabs[tab],
    section: section == null ? null : F.sections[section],
    submenu,
    stage: stage == null ? null : F.stages[stage],
    object: object == null ? null : F.objects[object],
    fit: fit == null ? null : F.fits[fit],
    exc,
    pathKind: F.pathKinds[kind],
  };
});
const COMPASS_BY_ID = new Map(COMPASS_ENTRIES.map((c) => [c.id, c]));
export const getCompassEntry = (id) => COMPASS_BY_ID.get(id) || null;
/** How well the rules predict the real menu paths (measured by the build). */
export const COMPASS_METRICS = F.metrics;

const OUT_OF_SCOPE = new Set(RULES.outOfScopeApps); // OneSite (Property Management), "(Application)" placeholders
const MENU_ENTRIES = COMPASS_ENTRIES.filter((c) => c.pathKind === 'menu' && c.app && !OUT_OF_SCOPE.has(c.app));

// Applications whose All tab is organized into home-page sections (Daily Tasks, Search & Find …).
const SECTION_SHARE = new Map();
for (const c of MENU_ENTRIES) {
  if (c.tab !== 'All') continue;
  const s = SECTION_SHARE.get(c.app) || { n: 0, withSection: 0 };
  s.n += 1;
  if (c.section && c.section !== 'More') s.withSection += 1;
  SECTION_SHARE.set(c.app, s);
}
export const appUsesSections = (app) => {
  const s = SECTION_SHARE.get(app);
  return Boolean(s && s.withSection / s.n >= 0.3);
};

// ---------------------------------------------------------------------------
// Visual map: applications × lifecycle stages
// ---------------------------------------------------------------------------

/** Rows of the city grid, largest application first; cells count real menu-path screens. */
export function buildGrid() {
  const byApp = new Map();
  for (const c of MENU_ENTRIES) {
    const row = byApp.get(c.app) || { app: c.app, total: 0, cells: Object.fromEntries(STAGE_KEYS.map((k) => [k, 0])), unstaged: 0 };
    row.total += 1;
    if (c.stage && row.cells[c.stage] != null) row.cells[c.stage] += 1;
    else row.unstaged += 1;
    byApp.set(c.app, row);
  }
  return [...byApp.values()].sort((a, b) => b.total - a.total);
}

/** Screens in one cell, grouped by submenu (largest list first). stage=null → the app's unstaged lists. */
export function cellSubmenus(app, stage) {
  const groups = new Map();
  for (const c of MENU_ENTRIES) {
    if (c.app !== app) continue;
    if (stage ? c.stage !== stage : c.stage && STAGE_KEYS.includes(c.stage)) continue;
    const key = [c.tab, c.section, c.submenu || '(tab root)'].filter(Boolean).join(' › ');
    if (!groups.has(key)) groups.set(key, { key, submenu: c.submenu || '(tab root)', items: [] });
    groups.get(key).items.push(c);
  }
  return [...groups.values()].sort((a, b) => b.items.length - a.items.length);
}

// ---------------------------------------------------------------------------
// Predict-then-reveal drill
// ---------------------------------------------------------------------------

// Seeded PRNG so a deck is reproducible (tests, "retry this deck").
export function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const shuffle = (arr, rand) => {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

const GERUNDS = {
  adding: 'Add', creating: 'Create', entering: 'Enter', voiding: 'Void', reversing: 'Reverse', deleting: 'Delete',
  editing: 'Edit', viewing: 'View', setting: 'Set', running: 'Run', printing: 'Print', importing: 'Import',
  exporting: 'Export', configuring: 'Configure', enabling: 'Enable', disabling: 'Disable', paying: 'Pay',
  closing: 'Close', opening: 'Open', reopening: 'Reopen', posting: 'Post', unposting: 'Unpost', approving: 'Approve',
  declining: 'Decline', generating: 'Generate', reconciling: 'Reconcile', applying: 'Apply', using: 'Use',
  changing: 'Change', customizing: 'Customize', duplicating: 'Duplicate', assigning: 'Assign', defining: 'Define',
  scheduling: 'Schedule', updating: 'Update', uploading: 'Upload', downloading: 'Download', transferring: 'Transfer',
  merging: 'Merge', inactivating: 'Inactivate', submitting: 'Submit', receiving: 'Receive', matching: 'Match',
  calculating: 'Calculate', recalculating: 'Recalculate', finding: 'Find', searching: 'Search', managing: 'Manage',
  processing: 'Process', splitting: 'Split', reclassing: 'Reclass', reclassifying: 'Reclassify', activating: 'Activate',
  disposing: 'Dispose', depreciating: 'Depreciate', publishing: 'Publish', emailing: 'Email', storing: 'Store',
  saving: 'Save', filtering: 'Filter', sorting: 'Sort', installing: 'Install', mapping: 'Map', linking: 'Link',
  requesting: 'Request', recording: 'Record', resolving: 'Resolve', refunding: 'Refund', depositing: 'Deposit',
  writing: 'Write', canceling: 'Cancel', cancelling: 'Cancel', removing: 'Remove', restoring: 'Restore',
  allocating: 'Allocate', amortizing: 'Amortize', attaching: 'Attach', marking: 'Mark', placing: 'Place',
  releasing: 'Release', sending: 'Send', tracking: 'Track', verifying: 'Verify', clearing: 'Clear',
};

/** "Voiding a Check" → "Void a check"; "Vendors List" → "Open the Vendors List". */
export function taskPrompt(name) {
  const m = /^([A-Z][a-z]+ing)\b\s*(.*)$/.exec(name || '');
  if (m && GERUNDS[m[1].toLowerCase()]) {
    const rest = m[2].replace(/\b([A-Z][a-z]+)\b/g, (w) => (w.length > 1 ? w.toLowerCase() : w));
    return `${GERUNDS[m[1].toLowerCase()]} ${rest}`.trim();
  }
  if (/\b(list|page|box|tab|report|register|workbench|queue)$/i.test(name)) return `Open the ${name}`;
  return name;
}

/** Stage options for step 2, depending on how the application organizes its menu. */
export function stageOptionsFor(app) {
  if (!appUsesSections(app)) {
    return [
      { key: 'all', label: 'All tab', hint: 'Working lists and tools' },
      { key: 'configure', label: 'Setup tab', hint: STAGES.configure.where },
    ];
  }
  return STAGE_KEYS.map((k) => ({ key: k, label: STAGES[k].label, hint: STAGES[k].where }));
}

/** The step-2 answer key for a screen, matching stageOptionsFor(). */
export const stageAnswer = (c) => (appUsesSections(c.app) ? c.stage : c.tab === 'Setup' ? 'configure' : 'all');

const drillable = (c) =>
  c.pathKind === 'menu' &&
  c.submenu &&
  c.tab &&
  !/^\(|^\[|^\$|^-$/.test(c.submenu) &&
  (appUsesSections(c.app) ? Boolean(c.stage) && (c.tab === 'Setup' || Boolean(c.section)) : true);

const DRILLABLE = MENU_ENTRIES.filter(drillable);
export const DRILLABLE_COUNT = DRILLABLE.length;
const APPS_BY_SIZE = buildGrid().map((r) => r.app);

/**
 * A drill deck of real screens. `trapShare` of the cards are screens the rules get wrong
 * (tagged with an exception), so learners meet the exceptions on purpose.
 */
export function buildDeck({ seed = Date.now(), size = 12, app = null, trapShare = 0.3 } = {}) {
  const rand = mulberry32(seed);
  const pool = DRILLABLE.filter((c) => !app || c.app === app);
  // One card per (app, submenu) keeps a deck from repeating the same list.
  const seen = new Set();
  const uniq = [];
  for (const c of shuffle(pool, rand)) {
    const k = `${c.app}|${c.submenu}`;
    if (seen.has(k)) continue;
    seen.add(k);
    uniq.push(c);
  }
  const traps = uniq.filter((c) => c.exc);
  const regular = uniq.filter((c) => !c.exc && c.fit === 'exact');
  const nTraps = Math.min(traps.length, Math.round(size * trapShare));
  const deck = [...traps.slice(0, nTraps), ...regular.slice(0, size - nTraps)];
  return shuffle(deck, rand).map((c) => makeQuestion(c, rand));
}

function pickDistractors(correct, candidates, n, rand) {
  const out = [];
  for (const c of shuffle(candidates, rand)) {
    if (c !== correct && !out.includes(c)) out.push(c);
    if (out.length >= n) break;
  }
  return out;
}

export function makeQuestion(c, rand = mulberry32(1)) {
  const pred = deduce(c.name);
  // Distractor apps: whatever the rules would guess (so traps are visible), then the big applications.
  const tempting = [pred.app, ...objectsIn(c.name).map((o) => o.app)].filter((a) => a && a !== c.app);
  const appChoices = shuffle(
    [c.app, ...pickDistractors(c.app, [...new Set(tempting)], 2, rand), ...pickDistractors(c.app, APPS_BY_SIZE.slice(0, 8), 3, rand)]
      .filter((a, i, arr) => arr.indexOf(a) === i)
      .slice(0, 4),
    rand
  );
  const sameApp = DRILLABLE.filter((d) => d.app === c.app && d.submenu !== c.submenu);
  const sameStage = sameApp.filter((d) => d.stage === c.stage);
  const subs = [...new Set([...shuffle(sameStage, rand), ...shuffle(sameApp, rand)].map((d) => d.submenu))];
  const submenuChoices = shuffle([c.submenu, ...subs.slice(0, 3)], rand);
  return {
    id: c.id,
    prompt: taskPrompt(c.name),
    screen: c,
    answer: { app: c.app, stage: stageAnswer(c), submenu: c.submenu },
    choices: { apps: appChoices, submenus: submenuChoices },
    prediction: pred,
  };
}

/** Grades one pick; returns per-step correctness and the explanation to show on reveal. */
export function grade(question, picks) {
  const { answer, screen, prediction } = question;
  const result = {
    app: picks.app === answer.app,
    stage: picks.stage === answer.stage,
    submenu: picks.submenu === answer.submenu,
  };
  result.all = result.app && result.stage && result.submenu;
  const exception = screen.exc ? getException(screen.exc) : null;
  const rulesRight = screen.fit === 'exact';
  result.explanation = {
    realPath: ['Applications', screen.app, screen.tab, screen.section, screen.submenu].filter(Boolean),
    rules: explainRules(prediction.rules, prediction),
    rulesPredicted: formatPath(prediction),
    rulesRight,
    exception,
    verdict: rulesRight
      ? 'The rules predict this screen exactly.'
      : exception
        ? `Exception ${exception.id}: the rules point to ${prediction.app || 'no application'}, but RealPage files it elsewhere.`
        : prediction.app === screen.app
          ? 'Right application; the list is a narrower variant the rules only approximate.'
          : 'A rule gap: the title does not name a strong business object.',
  };
  return result;
}

// ---------------------------------------------------------------------------
// Scenario box
// ---------------------------------------------------------------------------

const STOP = new Set(
  'a an the and or to of for in on at by with from into is are was were be been it its this that we our my your their i you they site need needs want wants has have had already just still after before when then how do does what where which should can'.split(' ')
);

const keywords = (text) =>
  normalize(text)
    .split(' ')
    .filter((w) => w.length >= 3 && !STOP.has(w))
    .map((w) => w.replace(/(ies|es|s)$/, ''));

function submenuLike(a, b) {
  if (!a || !b) return false;
  const x = normalize(a);
  const y = normalize(b);
  return x === y || x.startsWith(y) || y.startsWith(x);
}

/**
 * Walks a typed situation through steps 1-2-3 and lands on candidate screens.
 * Deterministic: synonyms, the object lexicon, tie-breakers, stage verbs and exception cues.
 */
export function matchScenario(text, { limit = 8 } = {}) {
  const raw = (text || '').trim();
  if (!raw) return null;
  const pred = deduce(raw, { scenario: true });
  const normalized = normalizeScenario(raw);
  const stateInfo = pred.state ? RULES.states.find((s) => s.state === pred.state) : null;
  const primary = pred.object ? OBJECT_BY_ID.get(pred.object) : null;

  // Other readings of the same words (a refund is AR *and* AP): one landing per other application.
  const alternates = [];
  const seenApps = new Set([pred.app]);
  for (const o of objectsIn(stripStates(normalized))) {
    if (seenApps.has(o.app)) continue;
    seenApps.add(o.app);
    alternates.push({ object: o.id, label: o.label, app: o.app, tab: o.home.tab, section: o.home.section, submenu: o.home.submenu === '=title' ? `${o.label} reports` : o.home.submenu });
  }

  const exceptions = EXCEPTIONS.filter((e) => e.cueRe && (e.cueRe.test(normalized) || e.cueRe.test(raw))).slice(0, 4);

  // Candidate screens: real menu-path screens scored against the deduction and the words typed.
  const words = keywords(normalized);
  const altApps = new Set(alternates.map((a) => a.app));
  const scored = [];
  for (const c of MENU_ENTRIES) {
    let score = 0;
    if (c.app === pred.app) score += 6;
    else if (altApps.has(c.app)) score += 2;
    else continue;
    if (pred.tab && c.tab === pred.tab) score += 1;
    if (pred.section && c.section === pred.section) score += 2;
    const subHit = submenuLike(c.submenu, pred.submenu);
    if (subHit) score += 5;
    if (pred.object && c.object === pred.object) score += 3;
    let hits = 0;
    for (const w of words) {
      if (c.entry._words.some((x) => x.startsWith(w))) hits += 1;
    }
    if (!hits && !subHit) continue;
    score += hits * 2.5;
    if (/_\d+$/.test(c.id)) score -= 0.5; // prefer the primary copy of a topic
    scored.push({ c, score });
  }
  scored.sort((a, b) => b.score - a.score || a.c.name.length - b.c.name.length);
  const candidates = [];
  const names = new Set();
  for (const { c } of scored) {
    if (names.has(c.name)) continue;
    names.add(c.name);
    candidates.push(c);
    if (candidates.length >= limit) break;
  }

  const ruleCards = explainRules(pred.rules, pred);
  const steps = [
    {
      n: 1,
      question: 'Which application?',
      answer: pred.app || 'No business object recognized',
      detail: primary ? `Business object: ${primary.label}.` : 'Name the record you are working with (invoice, vendor, bank account, journal entry …).',
      rules: ruleCards.filter((r) => r.step === 1),
    },
    {
      n: 2,
      question: 'Which tab or section?',
      answer: [pred.tab, pred.section].filter(Boolean).join(' › ') || '—',
      detail: pred.stage ? `${STAGES[pred.stage].label}: ${STAGES[pred.stage].question}` : '',
      rules: ruleCards.filter((r) => r.step === 2),
    },
    {
      n: 3,
      question: 'Which submenu or screen?',
      answer: pred.submenu || '—',
      detail: stateInfo ? stateInfo.hint : pred.action ? `Action: ${pred.action}.` : '',
      rules: ruleCards.filter((r) => r.step === 3),
    },
  ];
  return { input: raw, normalized, prediction: pred, steps, alternates, exceptions, candidates };
}

export const SCENARIO_EXAMPLES = [
  'Site entered the wrong invoice date and the batch is already posted',
  'Void a vendor check and restore the invoice',
  'Refund a resident security deposit after move-out',
  'Retainage invoice on a construction job',
  'Reverse a journal entry posted in a closed period',
  'Move cash from operating to the reserve account',
  'Accrue the utility bill we have not received',
  'Invoice is stuck in approval',
];

// ---------------------------------------------------------------------------
// Daily Hub tasks linked to the same business object (opens the 5-point MasteryModal)
// ---------------------------------------------------------------------------

/** Groups Daily Hub tasks by the business object the compass reads in their names. */
export function indexTasksByObject(tasks) {
  const map = new Map();
  for (const t of tasks || []) {
    const p = deduce(t.name, { scenario: true });
    if (!p.object) continue;
    if (!map.has(p.object)) map.set(p.object, []);
    map.get(p.object).push(t);
  }
  return map;
}
