// Screen index + fuzzy search over every screen in the nine RealPage module files.
//
// Runs on the compact pre-computed index (src/data/searchIndex.json: id, name, nav, moduleId,
// category, authority) and the module manifest, both generated by
// scripts/build_realpage_modules.py. The ~28 MB of full screen detail is never imported here;
// callers that need it use loadScreenById() / the useScreenDetail hook, which pull in the
// owning module on demand (data/moduleLoader).
//
// Built once at import time with pre-normalized text, so each keystroke only scans
// pre-lowercased strings. Pure JS (no React Native imports) so it can be unit-tested in Node.

import SEARCH_INDEX from '../data/searchIndex.json';
import MODULE_MANIFEST from '../data/moduleManifest.json';
import { getLoadedScreen, loadScreen } from '../data/moduleLoader';

export const MODULE_FILE_TO_ID = {
  '01_general_ledger': 'gl',
  '02_accounts_payable': 'ap',
  '03_cash_management': 'cash',
  '04_accounts_receivable': 'ar',
  '05_financial_close': 'close',
  '06_jobcost_capex_reserves': 'job_cost',
  '07_fixed_assets': 'fixed_assets',
  '08_budgeting_forecasting': 'budgeting',
  '09_reporting_admin': 'reporting',
};

/** Module summaries (title, color, icon, screen counts, submodule list) in app display order. */
export const MODULES = MODULE_MANIFEST;
const MODULE_BY_ID = new Map(MODULES.map((m) => [m.id, m]));
export const getModuleMeta = (moduleId) => MODULE_BY_ID.get(moduleId) || null;

// "A/P Invoice" -> "ap invoice", "G/L" -> "gl", "1099-NEC" -> "1099 nec"
export const normalize = (s) =>
  String(s || '')
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/(\w)\/(\w)/g, '$1$2')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

const ENTRIES = [];
const BY_ID = new Map();
const BY_SUBMODULE = new Map(); // submoduleId -> entries (display order)

// The index is written in manifest order (module, then submodule), so the manifest's per-submodule
// counts give every entry its submodule without storing it in the index.
let cursor = 0;
for (const mod of MODULES) {
  for (const sub of mod.submodules) {
    const list = [];
    for (let i = 0; i < sub.count; i++) {
      const raw = SEARCH_INDEX[cursor++];
      if (!raw || raw.moduleId !== mod.id) {
        throw new Error(`searchIndex.json is out of sync with moduleManifest.json at ${mod.id}/${sub.id}; run npm run build:modules`);
      }
      const name = normalize(raw.name);
      const entry = {
        id: raw.id,
        name: raw.name,
        nav: raw.nav,
        navParts: raw.nav ? raw.nav.split(' > ') : [],
        category: raw.category,
        authority: raw.authority,
        moduleId: mod.id,
        moduleTitle: mod.title,
        moduleShortCode: mod.shortCode,
        moduleColor: mod.color,
        submoduleId: sub.id,
        // pre-normalized search text
        _name: name,
        _words: name.split(' '),
        _nav: normalize(raw.nav),
        _cat: normalize(raw.category),
        _auth: normalize(raw.authority),
      };
      ENTRIES.push(entry);
      list.push(entry);
      BY_ID.set(raw.id, entry);
    }
    BY_SUBMODULE.set(sub.id, list);
  }
}
if (cursor !== SEARCH_INDEX.length) {
  throw new Error('searchIndex.json has entries the manifest does not count; run npm run build:modules');
}

export const SCREEN_COUNT = ENTRIES.length;
export const ALL_SCREEN_ENTRIES = ENTRIES;

export const getScreenEntry = (id) => BY_ID.get(id) || null;
export const hasScreen = (id) => BY_ID.has(id);
export const getSubmoduleEntries = (submoduleId) => BY_SUBMODULE.get(submoduleId) || [];

/** Full screen object if its module is already loaded, else null (never triggers a load). */
export const getScreenById = (id) => {
  const e = BY_ID.get(id);
  return e ? getLoadedScreen(e.moduleId, id) : null;
};

/** Loads the owning module on demand and resolves to the full screen object (null if unknown). */
export const loadScreenById = (id) => {
  const e = BY_ID.get(id);
  return e ? loadScreen(e.moduleId, id) : Promise.resolve(null);
};

// Bounded Levenshtein: returns max+1 as soon as the distance must exceed `max`.
export function editDistance(a, b, max = 2) {
  if (Math.abs(a.length - b.length) > max) return max + 1;
  let prev = new Array(b.length + 1);
  for (let j = 0; j <= b.length; j++) prev[j] = j;
  for (let i = 1; i <= a.length; i++) {
    const cur = [i];
    let rowMin = i;
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + cost);
      if (cur[j] < rowMin) rowMin = cur[j];
    }
    if (rowMin > max) return max + 1;
    prev = cur;
  }
  return prev[b.length];
}

function tokenScore(entry, token) {
  let best = 0;
  for (const w of entry._words) {
    if (w === token) return 10;
    if (w.startsWith(token)) best = Math.max(best, 7);
  }
  if (best) return best;
  if (entry._name.includes(token)) return 5;
  if (entry._nav.includes(token)) return 3;
  if (entry._cat.includes(token)) return 2;
  if (entry._auth.includes(token)) return 1;
  // typo tolerance on screen-name words: 1 edit for 4-6 letters, 2 edits for 7+
  if (token.length >= 4) {
    const max = token.length >= 7 ? 2 : 1;
    for (const w of entry._words) {
      if (w.length >= 3 && editDistance(token, w, max) <= max) return 4;
    }
  }
  return 0;
}

/**
 * Fuzzy search across all screens.
 * Every query token must match the screen (name, navigation, category, governing authority or a
 * near-miss name word); results are ranked by name matches first.
 * @returns {{ results: Array, total: number }}
 */
export function searchScreens(query, { moduleId = null, limit = 50 } = {}) {
  const q = normalize(query);
  if (!q) return { results: [], total: 0 };
  const tokens = Array.from(new Set(q.split(' ').filter(Boolean)));
  const scored = [];
  for (const entry of ENTRIES) {
    if (moduleId && entry.moduleId !== moduleId) continue;
    let score = 0;
    let ok = true;
    for (const t of tokens) {
      const s = tokenScore(entry, t);
      if (!s) {
        ok = false;
        break;
      }
      score += s;
    }
    if (!ok) continue;
    if (entry._name.includes(q)) score += 15;
    if (entry._name.startsWith(q)) score += 5;
    // prefer the primary copy of a topic over its "_2" variant from another manual
    if (!/_\d+$/.test(entry.id)) score += 0.5;
    scored.push({ entry, score });
  }
  scored.sort((a, b) => b.score - a.score || a.entry.name.length - b.entry.name.length);
  return { results: scored.slice(0, limit).map((s) => s.entry), total: scored.length };
}
